//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accepted_product
    {
        public int ID { get; set; }
        public int ID_dispatch { get; set; }
        public int quantity { get; set; }
        public int ID_product { get; set; }
    
        public virtual Dispatch Dispatch { get; set; }
        public virtual Ranges Ranges { get; set; }
    }
}
