//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dispatch()
        {
            this.Accepted_product = new HashSet<Accepted_product>();
            this.Dispatch_product = new HashSet<Dispatch_product>();
        }
    
        public int ID_dispatch { get; set; }
        public System.DateTime Dates { get; set; }
        public int ID_employee { get; set; }
        public int ID_klients { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accepted_product> Accepted_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dispatch_product> Dispatch_product { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Klients Klients { get; set; }
    }
}
