//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SKLADEntities : DbContext
    {
        public SKLADEntities()
            : base("name=SKLADEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accepted_product> Accepted_product { get; set; }
        public virtual DbSet<Dispatch> Dispatch { get; set; }
        public virtual DbSet<Dispatch_product> Dispatch_product { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Klients> Klients { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Product_on_warehouse> Product_on_warehouse { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<Ranges> Ranges { get; set; }
        public virtual DbSet<Unit_of_measurement> Unit_of_measurement { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
    }
}
