//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_on_warehouse
    {
        public int ID_Product_on_warehouse { get; set; }
        public int ID_Product { get; set; }
        public int ID_Warehouse { get; set; }
        public int quantity { get; set; }
    
        public virtual Ranges Ranges { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
