//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Providers
    {
        public int ID_Provider { get; set; }
        public System.DateTime Dates { get; set; }
        public int ID_Receiving_employee { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
