//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ranges()
        {
            this.Accepted_product = new HashSet<Accepted_product>();
            this.Dispatch_product = new HashSet<Dispatch_product>();
            this.Product_on_warehouse = new HashSet<Product_on_warehouse>();
        }
    
        public int ID_product { get; set; }
        public string Names_range { get; set; }
        public int Price { get; set; }
        public int Unit_of_measurement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accepted_product> Accepted_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dispatch_product> Dispatch_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_on_warehouse> Product_on_warehouse { get; set; }
        public virtual Unit_of_measurement Unit_of_measurement1 { get; set; }
    }
}
